### PR TITLE
fix rstudio service ports

### PR DESCRIPTION
**Pull request by sergkudinov**
RStudio container exposes port 8787.

### CODE REVIEW

**Comment by fcomte** [comment]
why do you prefer to use port 8787 in stead of 80 ?

**Comment by sergkudinov** [comment]
It is not a question of preference.
The container image exposes 8787 and it must be used, it is also a case [here](https://github.com/InseeFrLab/helm-charts-interactive-services/blob/main/charts/rstudio/templates/statefulset.yaml#L113).

**Comment by fcomte** [comment]
https://github.com/InseeFrLab/helm-charts-interactive-services/blob/ff11212bc99cc2d78f10e4e27812a889493062c3/charts/library-chart/templates/_service.tpl#L18

I think we use targetPort http and name all the port http in deployment ... It's working but it's not a very good idea ... I think we should modify this tpl too

**Comment by sergkudinov** [comment]
> I think we use targetPort http and name all the port http in deployment ... It's working but it's not a very good idea ... I think we should modify this tpl too

Not sure how to fix it considering your words, I leave it up to you. You can close this PR if you want.

**Comment by avouacr** [comment]
Fixed in 401d40f5b19311661c6a3cd5feaa62ccbf8736b3 and af16350b6863be23113b71ccfb18b92f8e0daaca. We now use the port exposed by the container as service port, for improved clarity.

**Pull request closed without merging**
